version: '3.9'
networks:
        net:
                driver: bridge
services:
        app:
                build: ./app
                ports:
                        - "5000:5000"
                depends_on: 
                        - db
                networks:
                        - net
                volumes:
                        - ./app:/app
                links:
                        - db
        db:
                image: mongo:5.0
                ports:
                        - "27017:27017"
                expose:
                        - "5000"
                        - "27017"
                networks:
                        - net

